# Generated by Django 4.2.7 on 2025-11-17 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_create_user_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "Вход в систему"),
                            ("logout", "Выход из системы"),
                            ("register", "Регистрация"),
                            ("profile_update", "Обновление профиля"),
                            ("order_create", "Создание заказа"),
                            ("order_view", "Просмотр заказа"),
                            ("product_view", "Просмотр товара"),
                            ("cart_add", "Добавление в корзину"),
                            ("cart_remove", "Удаление из корзины"),
                            ("cart_update", "Обновление корзины"),
                            ("admin_access", "Доступ к админке"),
                            ("permission_denied", "Отказ в доступе"),
                            ("other", "Другое"),
                        ],
                        max_length=50,
                        verbose_name="Тип действия",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание действия"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Путь запроса"
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Метод запроса"
                    ),
                ),
                (
                    "status_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="HTTP статус"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог активности пользователя",
                "verbose_name_plural": "Логи активности пользователей",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="users_usera_created_774eb1_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_usera_user_id_5cb3ab_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="users_usera_action__a3303b_idx",
                    ),
                ],
            },
        ),
    ]
