# Generated by Django 4.2.7 on 2026-01-21 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_create_usercard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="delivery_apartment",
        ),
        migrations.RemoveField(
            model_name="user",
            name="delivery_building",
        ),
        migrations.RemoveField(
            model_name="user",
            name="delivery_city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="delivery_entrance",
        ),
        migrations.RemoveField(
            model_name="user",
            name="delivery_floor",
        ),
        migrations.RemoveField(
            model_name="user",
            name="delivery_street",
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("street", models.CharField(max_length=200, verbose_name="Улица")),
                ("house", models.CharField(max_length=20, verbose_name="Дом")),
                (
                    "block",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Корпус/Строение",
                    ),
                ),
                (
                    "entrance",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Подъезд"
                    ),
                ),
                (
                    "floor",
                    models.IntegerField(blank=True, null=True, verbose_name="Этаж"),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Квартира/Офис",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Основной адрес"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
            },
        ),
    ]
