# Generated by Django 4.2.7 on 2026-01-25 21:46

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_user_delivery_apartment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[],
            options={
                "verbose_name": "Курьер",
                "verbose_name_plural": "Курьеры",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
