# Generated by Django 4.2.7 on 2026-01-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_courier"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Аватар"
            ),
        ),
    ]
