# Generated by Django 4.2.7 on 2026-05-05 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Только для ответов поддержки: укажите сообщение клиента (в админке удобнее блок «Ответы» ниже).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="support.supportmessage",
                verbose_name="Ответ на сообщение",
            ),
        ),
    ]
