# Generated by Django 4.2.7 on 2026-01-21 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="shift",
            new_name="shifts_shif_courier_5ddf8b_idx",
            old_name="shifts_shif_courier_ended_a_idx",
        ),
        migrations.RenameIndex(
            model_name="shift",
            new_name="shifts_shif_courier_0b5819_idx",
            old_name="shifts_shif_courier_started_idx",
        ),
    ]
