# Generated by Django 4.2.7 on 2026-01-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "shifts",
            "0002_rename_shifts_shif_courier_ended_a_idx_shifts_shif_courier_5ddf8b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="is_confirmed",
            field=models.BooleanField(
                default=False, verbose_name="Подтверждена админом"
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("started", "Начата"),
                    ("ended", "Завершена"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Начало смены"
            ),
        ),
    ]
