# Generated by Django 4.2.7 on 2025-11-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_create_sql_components"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество на складе"
            ),
        ),
    ]
