# Generated by Django 4.2.7 on 2026-02-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_product_stock_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Уникальный штрихкод товара для сканирования",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Штрихкод",
            ),
        ),
    ]
