# Generated by Django 4.2.7 on 2026-03-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_promotion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-check",
                        help_text="Класс Font Awesome, например: fas fa-truck",
                        max_length=100,
                        verbose_name="Иконка",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Текст")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Преимущество",
                "verbose_name_plural": "Преимущества",
                "ordering": ["order"],
            },
        ),
    ]
