# Generated by Django 4.2.7 on 2026-05-05 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_favourite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Растровое изображение: JPG, PNG, GIF или WebP. Не загружайте сохранённые HTML-страницы или PDF.",
                null=True,
                upload_to="banners/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("jpg", "jpeg", "png", "gif", "webp")
                    )
                ],
                verbose_name="Фоновое изображение",
            ),
        ),
    ]
