# Generated by Django 4.2.7 on 2026-05-05 01:18

import django.core.validators
from django.db import migrations, models


def move_banner_images_banners_to_hero_slides(apps, schema_editor):
    """Файлы из media/banners/ → media/hero_slides/ и обновление путей в БД (обход AdBlock по URL /banners/)."""
    import shutil
    from pathlib import Path

    from django.conf import settings

    Banner = apps.get_model("catalog", "Banner")
    media = Path(settings.MEDIA_ROOT)
    for banner in Banner.objects.exclude(image="").iterator():
        old_name = banner.image.name
        if not old_name.startswith("banners/"):
            continue
        new_name = "hero_slides/" + old_name.removeprefix("banners/")
        old_path = media / old_name
        new_path = media / new_name
        if new_path.is_file():
            banner.image.name = new_name
            banner.save(update_fields=["image"])
            continue
        if old_path.is_file():
            new_path.parent.mkdir(parents=True, exist_ok=True)
            if not new_path.exists():
                shutil.move(str(old_path), str(new_path))
            banner.image.name = new_name
            banner.save(update_fields=["image"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_banner_image_validators"),
    ]

    operations = [
        migrations.RunPython(move_banner_images_banners_to_hero_slides, noop_reverse),
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Растровое изображение: JPG, PNG, GIF или WebP. Не загружайте сохранённые HTML-страницы или PDF.",
                null=True,
                upload_to="hero_slides/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("jpg", "jpeg", "png", "gif", "webp")
                    )
                ],
                verbose_name="Фоновое изображение",
            ),
        ),
    ]
