# Generated by Django 4.2.7 on 2026-01-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_add_courier_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_lng",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Долгота (Lng)"
            ),
        ),
    ]
