# Generated by Django 4.2.7 on 2026-01-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_order_delivery_lng"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_lat",
            field=models.FloatField(blank=True, null=True, verbose_name="Широта (Lat)"),
        ),
    ]
