# Generated by Django 4.2.7 on 2026-01-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0007_order_delivery_lat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_address",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_apartment",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Квартира/Офис"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_block",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Корпус/Строение"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_city",
            field=models.CharField(default="", max_length=100, verbose_name="Город"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_entrance",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Подъезд"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_floor",
            field=models.IntegerField(blank=True, null=True, verbose_name="Этаж"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_house",
            field=models.CharField(default="", max_length=20, verbose_name="Дом"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_street",
            field=models.CharField(default="", max_length=200, verbose_name="Улица"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Широта (Lat)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Долгота (Lng)",
            ),
        ),
    ]
