# Generated by Django 4.2.7 on 2026-01-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0008_remove_order_delivery_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="courier_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Вознаграждение курьера",
            ),
        ),
    ]
