# Generated by Django 4.2.7 on 2026-01-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0009_order_courier_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="delivery_photos/",
                verbose_name="Фотоотчет доставки",
            ),
        ),
    ]
