# Generated by Django 4.2.7 on 2026-01-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0010_order_delivery_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_photo",
        ),
        migrations.AddField(
            model_name="order",
            name="photo_report",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="reports/",
                verbose_name="Фотоотчет (бесконтактная доставка)",
            ),
        ),
    ]
