# Generated by Django 4.2.7 on 2026-01-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0011_remove_order_delivery_photo_order_photo_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("COOKING", "В сборке"),
                    ("READY", "Собран"),
                    ("SHIPPING", "Доставляется"),
                    ("DELIVERED", "Доставлен"),
                    ("CANCELLED", "Отменен"),
                ],
                default="COOKING",
                max_length=20,
                verbose_name="Статус заказа",
            ),
        ),
    ]
