# Generated by Django 4.2.7 on 2026-02-02 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0012_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="picker",
            field=models.ForeignKey(
                blank=True,
                help_text="Сборщик, назначенный на сборку заказа",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="picking_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сборщик",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="verification_code",
            field=models.CharField(
                blank=True,
                help_text="QR-код для передачи заказа курьеру",
                max_length=8,
                null=True,
                unique=True,
                verbose_name="Код верификации",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_scanned",
            field=models.BooleanField(
                default=False,
                help_text="Отметка о том, что товар отсканирован сборщиком",
                verbose_name="Отсканирован",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAID", "Оплачен"),
                    ("ASSEMBLING", "На сборке"),
                    ("ASSEMBLED", "Собран"),
                    ("SHIPPING", "Доставляется"),
                    ("DELIVERED", "Доставлен"),
                    ("CANCELLED", "Отменен"),
                ],
                default="PAID",
                max_length=20,
                verbose_name="Статус заказа",
            ),
        ),
    ]
