# Generated by Django 4.2.7 on 2026-02-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0013_order_picker_order_verification_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Оплачен"),
                    ("ASSEMBLING", "В сборке"),
                    ("ASSEMBLED", "Собран"),
                    ("SHIPPING", "Доставляется"),
                    ("DELIVERED", "Доставлен"),
                    ("CANCELLED", "Отменен"),
                ],
                default="PAID",
                max_length=20,
                verbose_name="Статус заказа",
            ),
        ),
    ]
