# Generated by Django 4.2.7 on 2026-02-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0014_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "В ожидании"),
                    ("ASSEMBLING", "В сборке"),
                    ("ASSEMBLED", "Собран"),
                    ("SHIPPING", "Доставляется"),
                    ("DELIVERED", "Доставлен"),
                    ("CANCELLED", "Отменен"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Статус заказа",
            ),
        ),
    ]
