# Generated by Django 4.2.7 on 2026-02-13 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_product_barcode"),
        ("cart", "0015_order_default_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="custom_product_name",
            field=models.CharField(
                blank=True,
                help_text="Название товара, указанное вручную (для замен без привязки к каталогу)",
                max_length=255,
                null=True,
                verbose_name="Пользовательское название товара",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="expected_barcode",
            field=models.CharField(
                blank=True,
                help_text="Штрихкод, по которому собирается товар (для замен может отличаться от товара каталога)",
                max_length=50,
                null=True,
                verbose_name="Ожидаемый штрихкод товара",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_replacement",
            field=models.BooleanField(
                default=False,
                help_text="Пометка, что позиция была добавлена как замена в процессе сборки",
                verbose_name="Это замена товара",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="replaced_item",
            field=models.ForeignKey(
                blank=True,
                help_text="К какой исходной позиции относится данная замена (опционально)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replacements",
                to="cart.orderitem",
                verbose_name="Заменяемая позиция",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="replacement_comment",
            field=models.CharField(
                blank=True,
                help_text="Причина или пояснение замены (заполняется сборщиком)",
                max_length=255,
                null=True,
                verbose_name="Комментарий к замене",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Основной товар позиции. Может быть пустым для вручную добавленной замены",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
                verbose_name="Товар",
            ),
        ),
    ]
